name: CI/CD Deploy to VPS using DockerHub

on:
  push:
    branches:
      - SET-317-API

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Cài Nginx nếu chưa có
        run: |
          which nginx || (apt update && apt install -y nginx)

      - name: Copy file cấu hình Nginx
        run: |
          echo '
          server {
              listen 80;
              server_name cicd.com;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
          ' | tee /etc/nginx/sites-available/cicd.com

      - name: Kiểm tra cấu hình và reload Nginx
        run: |
          nginx -t
          systemctl reload nginx

      - name: Pull latest image từ DockerHub
        run: docker pull minhman2002/set2025-api:latest

      - name: Stop và remove container cũ nếu có
        run: |
          docker stop set2025 || true
          docker rm set2025 || true

      - name: Run container mới
        run: docker run -d -p 3000:3000 --name set2025 minhman2002/set2025-api:latest
