name: CI/CD Deploy to VPS using DockerHub

on:
  push:
    branches:
      - SET-317-API

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest image từ DockerHub
        run: docker pull minhman2002/set2025-api:latest

      - name: Stop và remove container cũ nếu có
        run: |
          docker stop set2025 || true
          docker rm set2025 || true

      - name: Run container mới
        run: docker run -d -p 3000:3000 --name set2025 minhman2002/set2025-api:latest
